on:
  workflow_dispatch: 
    inputs:
      release:
        description: "Make a new GitHub/Zenodo release with this run?"
        required: true
        type: boolean

name: hpc_sub.yml

jobs:
  states:
    runs-on: matrix-concurrent
    steps:
      - run: | 
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/"$KEY_NAME"
          sudo chmod 600 ~/.ssh/"$KEY_NAME"
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          KEY_NAME: ${{ secrets.KEY_FILE_NAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_HPC }}
          SSH_KNOWN_HOSTS: ${{ secrets.AUTH_HOSTS }}
      - run: ssh -i ~/.ssh/"$KEY_NAME" -J $SEC_USER@$FHOST $SEC_USER@$SHOST  ". /usr/local/bin/slurm-selector.sh ocelote; cd $HPC_FOLDER_PATH ; sbatch -A $ACCOUNT -t 02:00:00 --array=1-48 -p standard -N 1 -n 6 coordinator.sh"
        env:
          HPC_FOLDER_PATH: ${{ secrets.HPC_FOLDER_PATH}}
          ACCOUNT: ${{ secrets.ACCOUNT_NAME}}
          KEY_NAME: ${{ secrets.KEY_FILE_NAME }}
          SEC_USER: ${{ secrets.SECRET_USER}}
          FHOST: ${{ secrets.FIRST_HOST}}
          SHOST: ${{ secrets.SECOND_HOST}}

