on:
  workflow_dispatch: 
    inputs:
      release:
        description: "Make a new GitHub/Zenodo release with this run?"
        required: true
        type: boolean

name: hpc_sub.yml

jobs:
  states:
    runs-on: matrix-concurrent
    steps:
      - run: | 
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/"$KEY_FILE_NAME"
          sudo chmod 600 ~/.ssh/"$KEY_FILE_NAME"
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        env:
          KEY_NAME: ${{ secrets.KEY_FILE_NAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_HPC }}
          SSH_KNOWN_HOSTS: ${{ secrets.AUTH_HOSTS }}
      - run: echo $SEC_USER@$FHOST $SEC_USER@$SHOST
        env:
          SEC_USER: ${{ secrets.SECRET_USER}}
          FHOST: ${{ secrets.FIRST_HOST}}
          SHOST: ${{ secrets.SECOND_HOST}}
      - run: ssh -i ~/.ssh/private.key -J $SEC_USER@$FHOST $SEC_USER@$SHOST hostname -i
        env:
          SEC_USER: ${{ secrets.SECRET_USER}}
          FHOST: ${{ secrets.FIRST_HOST}}
          SHOST: ${{ secrets.SECOND_HOST}}

